version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi-crud
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - SECRET_API_KEY=supersecret123
